color: null
fieldLayouts:
  e5ab5996-6b42-48b8-97f2-2d536c1a230b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-22T23:53:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5b1568d2-51f2-47b8-8fad-38e4eb332fb8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T23:58:22+00:00'
            elementCondition: null
            fieldUid: f68a3386-e428-4757-9750-aa0f8cc133d1 # Slide Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bbae1ef-f70a-4a45-8bf7-971ad0a47cce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T23:58:22+00:00'
            elementCondition: null
            fieldUid: b0801027-28ca-4e94-b7b9-7dd7cb331639 # Slide Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6cee8db-847a-4618-808c-8f4ec29bcbdd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T23:58:22+00:00'
            elementCondition: null
            fieldUid: bdc28bb9-c07b-4b1e-9999-99312264f08e # Slide Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df975d8c-d804-48ec-af49-5e1df4131dea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5606539a-895c-4f72-b8f7-6ed4b3c1f3cf
        userCondition: null
handle: blockSlide
hasTitleField: true
icon: cube
name: 'Block: Slide'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
