color: null
fieldLayouts:
  83f1b97b-d0f9-49bb-9ae9-0bcd83b6d259:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T22:47:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d027432-d6cb-4653-af5e-0f089530294c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-06T23:44:22+00:00'
            elementCondition: null
            fieldUid: 26fbff70-0997-4ddd-a8d8-96e64b850188 # Featured Works Block Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad0952ae-0694-444c-9a28-181e74d30feb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-06T23:44:22+00:00'
            elementCondition: null
            fieldUid: 481a7e66-9921-4b62-9821-8aa4e542ff38 # Featured Works Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c77d61f1-6d30-4160-a120-3c1f9f0d342f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-10T19:20:12+00:00'
            elementCondition: null
            fieldUid: cb27dbe3-1802-4914-bbe2-7a4a53f42e1d # Featured Works Photos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5588881b-890e-4024-893e-6036808c4c72
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ffb95827-7fa0-45f3-827f-36045ed02e4e
        userCondition: null
handle: featuredWorksBlock
hasTitleField: true
icon: null
name: 'Featured Works Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
