color: null
fieldLayouts:
  a39867a0-2f2f-4fdf-ba06-612567d8761b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T02:43:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5c02115c-89e6-433a-8e13-d3bcdc8dd1d0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e7859b6-fa90-416a-a787-d0d456f9b1c3
        userCondition: null
handle: header
hasTitleField: true
icon: cube
name: 'Block: Header'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
