color: null
fieldLayouts:
  8bc26d93-4ea6-4475-9be0-108a63df872d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T02:56:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 36269699-43fa-46b3-82e1-f9bfdea7097c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T02:58:00+00:00'
            elementCondition: null
            fieldUid: fcd2475b-f27b-406f-a8a4-96b0bf65fab9 # Page Spacer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7defa900-4241-4648-89fd-7d48d57c45bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d1c24e3a-ea76-4f7d-8ce5-305451f5ab6e
        userCondition: null
handle: pageSpacer
hasTitleField: true
icon: null
name: 'Page Spacer'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
