color: null
fieldLayouts:
  f7c829d1-d8a9-4448-803c-389e7f582819:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-22T00:59:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b04ad3ad-9de0-459e-9046-e237870551a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T22:32:11+00:00'
            elementCondition: null
            fieldUid: 5d3e6e09-5f5c-4369-b4fb-bd9410073b43 # Page Builder Option: Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eaaa2cb-40ef-4e82-99b4-c85216d82681
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T01:23:41+00:00'
            elementCondition: null
            fieldUid: 6a2e7606-6a81-4adb-8538-b27df2adb73e # Page Slides
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d35dcac-407b-4818-a01e-071644c50f85
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00c02959-1021-4664-9b2e-60d8d77c69b4
        userCondition: null
handle: pageBuilderSliderBlock
hasTitleField: true
icon: cube
name: 'Page Builder: Slider Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
