color: null
fieldLayouts:
  3883be59-53ef-44d9-939c-9f8dbbf2a5d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T03:03:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0e3cf504-c02f-4b8b-8149-df38278a54e8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T03:06:05+00:00'
            elementCondition: null
            fieldUid: 03abafd4-804b-4730-a878-f77b4520e502 # Page Gallery Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d3ccb09-8c62-42b7-b890-84a75f7a6020
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T03:06:05+00:00'
            elementCondition: null
            fieldUid: 36fcd9d8-6671-40b1-887b-84c395c8c6da # Page Gallery Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 648d2a5a-0281-4b54-bdc3-ca7abe822366
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 379fb26c-dfc4-4f55-a5e1-cd4ddb695841
        userCondition: null
handle: pageBuilderGalleryBlock
hasTitleField: true
icon: cube
name: 'Page Builder: Gallery Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
