color: null
fieldLayouts:
  7aa9f0f9-b97a-4420-ac74-1d4ae74e7c25:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T02:57:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a9e481c-dbcf-40f9-8e30-8ef6ca591598
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T03:00:38+00:00'
            elementCondition: null
            fieldUid: 450da273-b412-48fc-bc9e-70a49eb8e206 # Content Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a523c4d-6ffe-467f-8323-b52570aba6a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T14:34:48+00:00'
            elementCondition: null
            fieldUid: 3df712b7-085b-48cc-8a30-26fe0cf880fd # Content Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6dc35cd-06b5-4406-a069-bce633a24ec6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T03:00:38+00:00'
            elementCondition: null
            fieldUid: 01914777-7aec-4ffe-b263-513b6e67154f # Content Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bf52773-84e5-4ae8-b8f1-0b7ec6836444
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T14:34:48+00:00'
            elementCondition: null
            fieldUid: c5536bad-aee8-49f4-aa42-0ba6c051dfc0 # Content Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6819a7ac-1b4e-4a95-832d-a78ea24a8c5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f151dc3a-c891-4d7f-9f5a-efdcf6a61065
        userCondition: null
handle: pageBuilderContentBlock
hasTitleField: true
icon: cube
name: 'Page Builder: Content Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
