color: null
fieldLayouts:
  8bb3b683-bc3d-423a-b8e6-42bdcafbef8e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-01T19:08:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 57f1b6a9-fd9f-4fdd-a183-e6fc49b18082
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-01T19:13:25+00:00'
            elementCondition: null
            fieldUid: fbdf5212-75c7-4c55-a84d-1fe336d63dfc # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db74c9db-adce-4c5b-86ef-d0b4d34738b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53f2d80f-7562-45a4-9dcd-a51e8f31a1b0
        userCondition: null
handle: pageLayout
hasTitleField: true
icon: table-layout
name: 'Page Layout'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
