color: null
fieldLayouts:
  37b6245f-9790-4ac5-9636-b4c9b825adfd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-22T17:37:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 939c50d7-a10d-4d57-a14d-f1207beb1ad9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T20:51:32+00:00'
            elementCondition: null
            fieldUid: 5d3e6e09-5f5c-4369-b4fb-bd9410073b43 # Page Builder Option: Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa828645-37b4-4b41-8383-b9755d98183d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T17:59:20+00:00'
            elementCondition: null
            fieldUid: 0c378192-32e9-4634-a22f-5a0646bbe23e # Card Kicker
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54b4ef8a-e3c4-4ed8-b79b-934ed46daa50
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T00:16:09+00:00'
            elementCondition: null
            fieldUid: 83c34dc7-2085-49ef-ba2c-a0f4f898807c # Card Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10e128b8-9ee2-4970-ab10-7e466961e575
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T00:16:09+00:00'
            elementCondition: null
            fieldUid: d0f439da-693a-43e8-a9e6-0a5bed47b5eb # Card Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 199d1ac5-36fa-4dc2-9ebc-5fbb82c36339
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T00:16:09+00:00'
            elementCondition: null
            fieldUid: e558cbdd-03de-4723-a362-60fa829e85b3 # Card Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26c755e5-e428-4e1c-8fa0-8b7a3329014f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T19:01:35+00:00'
            elementCondition: null
            fieldUid: b94fe730-955c-4213-9c8b-37178fbd0e25 # Card Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8505b74-7f77-431d-9d11-14d2bca16ef6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T17:59:20+00:00'
            elementCondition: null
            fieldUid: 61b701ed-160d-4f78-8ee6-f775dc98e7ac # Featured Works Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad6b5b81-6b13-4736-b68b-d7b5dcceb817
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T17:59:20+00:00'
            elementCondition: null
            fieldUid: 12514558-49b6-40e0-a01a-5858740c93cc # Featured Works Entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a51e58aa-2832-4510-8d97-84c3e4d593f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a681aeb3-767c-409e-83b6-a8091dd14fea
        userCondition: null
handle: pageBuilderFeaturedWorksBlock
hasTitleField: true
icon: cube
name: 'Page Builder: Featured Works Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
