color: null
fieldLayouts:
  37d203b3-288a-4bff-975f-e1ed3e065052:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T03:16:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fc603f9b-2fbf-40c4-9589-4dd5061dce76
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T03:18:38+00:00'
            elementCondition: null
            fieldUid: 5f67fcef-4f51-4832-a46c-d1f9fe66abc0 # Page Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fbeda38-8fbf-4955-8097-0760f1a8f159
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f0346db-66ce-4f1f-8555-ff57b9ed1da9
        userCondition: null
handle: pageForm
hasTitleField: true
icon: ''
name: 'Page Form'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
