color: null
fieldLayouts:
  e67d20cd-c4a4-4122-b443-4fda767792cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T00:05:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 87654127-5bef-4110-be58-e68fd08733c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T00:12:43+00:00'
            elementCondition: null
            fieldUid: 40154e12-d51d-4237-badf-a11bfc0ab075 # Slider Block Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e0ab290-94bd-40b8-a140-b3b32a40e3ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 04858c6b-8832-4a63-aa5a-841e44c720f1
        userCondition: null
handle: sliderBlock
hasTitleField: true
icon: ''
name: 'Slider Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
