color: null
fieldLayouts:
  d4b012cb-2fae-4fb9-ad59-1018bcb1286a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-01T20:35:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8a61594c-604f-44ea-9b7a-03fe38b58c35
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-01T20:37:23+00:00'
            elementCondition: null
            fieldUid: fcd2475b-f27b-406f-a8a4-96b0bf65fab9 # Page Spacer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28ae7b41-22bd-4bfb-80d9-71c517a95e1c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65b39d7f-90e2-4eb9-8153-2c8326e4a6b5
        userCondition: null
handle: spacer
hasTitleField: true
icon: cube
name: 'Block: Spacer'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
