color: null
fieldLayouts:
  b247bbe4-9a5f-4d72-ba70-54f5f5f3cf2b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T22:50:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 507c546b-d7eb-4a7f-9cb1-699fab88aff0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T22:31:43+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\MatrixFieldConditionRule
                  operator: in
                  uid: faa56fbe-6873-4b25-825e-b74efab8337f
                  values:
                    - 00e29050-57a6-4df7-b274-b36a66e19736 # Page Builder: Full Column Content
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 5d3e6e09-5f5c-4369-b4fb-bd9410073b43 # Page Builder Option: Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85f5e90d-7811-4cc5-92ac-cba785a7349e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-12T02:54:17+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\MatrixFieldConditionRule
                  operator: in
                  uid: 2d8024c9-d203-4327-9400-646c396ad50d
                  values:
                    - 00e29050-57a6-4df7-b274-b36a66e19736 # Page Builder: Full Column Content
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: dd78bdbf-3b91-4778-bae3-8b09ac060032 # Page Builder Option: Background Image Toggle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd4ed8bf-a698-4ac3-9033-d9a8a63920d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T19:16:01+00:00'
            elementCondition: null
            fieldUid: 0c378192-32e9-4634-a22f-5a0646bbe23e # Card Kicker
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 901a20d7-08d7-4568-9368-6f8760f2f21e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T00:12:08+00:00'
            elementCondition: null
            fieldUid: 83c34dc7-2085-49ef-ba2c-a0f4f898807c # Card Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d408564e-a99b-4d0f-a71d-ad5f1d348aa0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T00:12:08+00:00'
            elementCondition: null
            fieldUid: d0f439da-693a-43e8-a9e6-0a5bed47b5eb # Card Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34bfeb37-6ec1-4ca1-b2d8-fc68c84d1c07
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T00:12:08+00:00'
            elementCondition: null
            fieldUid: e558cbdd-03de-4723-a362-60fa829e85b3 # Card Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 364c4564-3d90-4c00-ad82-bd3dec3365d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T00:12:08+00:00'
            elementCondition: null
            fieldUid: 479fc44e-aa39-410b-9c74-5e1ae5c00c7e # Split Media Block Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bb0eccc-ccec-4ca7-89ba-be84e88c62c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T00:28:08+00:00'
            elementCondition: null
            fieldUid: 3d0151b1-3180-4665-8e2f-be7c0d1f1452 # Split Media Block Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58ddb52d-26b9-42cb-baa4-5cc48533c9ec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-31T20:09:26+00:00'
            elementCondition: null
            fieldUid: 68416f2f-16cf-49ab-83e7-e6b4b097e19d # Split Media Block Mobile Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4dbeac2-a6b5-442e-90a1-ead8eada679c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 58285e04-91ab-489e-b54b-ac4cbe4db201
        userCondition: null
handle: splitMedia
hasTitleField: true
icon: cube
name: 'Block: Split Media'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
