color: null
fieldLayouts:
  b247bbe4-9a5f-4d72-ba70-54f5f5f3cf2b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T22:50:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 507c546b-d7eb-4a7f-9cb1-699fab88aff0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T00:28:08+00:00'
            elementCondition: null
            fieldUid: f9de5f77-9be5-458f-82a1-6460ca454203 # Two Column Block Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d31035a1-a67f-4a9d-83ee-5219c38d7230
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T00:28:08+00:00'
            elementCondition: null
            fieldUid: 44da612c-bbaf-434b-bbbb-1668252f0f43 # Two Column Block Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae199416-8210-4925-a4ac-6d404629fab9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T00:28:08+00:00'
            elementCondition: null
            fieldUid: 7034c2c9-2683-438f-bf87-296f2b9783a3 # Two Column Block Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4746689-6a8b-44cd-8660-3c97e2b990c5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T00:28:08+00:00'
            elementCondition: null
            fieldUid: 3d0151b1-3180-4665-8e2f-be7c0d1f1452 # Two Column Block Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58ddb52d-26b9-42cb-baa4-5cc48533c9ec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T00:28:08+00:00'
            elementCondition: null
            fieldUid: fa0732ba-e924-456d-8e2c-4666006edb64 # Two Column Block Reverse
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97967c73-89e9-443c-9ed4-3c142b633815
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 58285e04-91ab-489e-b54b-ac4cbe4db201
        userCondition: null
handle: twoColumnBlock
hasTitleField: true
icon: ''
name: 'Two Column Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
