defaultPlacement: end
fieldLayouts:
  d1d1165c-1bdc-44ab-bc56-c7c5290669c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T15:03:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 21b4b147-53f2-4fd4-833d-280964a77f75
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7d208bd-8336-4651-9252-c09a2b748757
        userCondition: null
handle: season
name: Season
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: b22e1618-a236-4261-a600-26fce6c391a9
