defaultPlacement: end
fieldLayouts:
  4002c3a2-e18f-40c8-b29d-7193100db2b8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T14:56:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 02d23659-a9bc-4a93-ad10-52aae04164f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e2ed9590-b076-4ccf-ba6a-2ab21a979e76
        userCondition: null
handle: state
name: State
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 9761ae7e-3def-463a-864f-e86205b6f473
