altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  df3a69ae-0a4b-4345-8cc3-fef5d992beab:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T17:42:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ac396450-77ca-41d7-ba62-056f8d117705
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 69a00198-5dfb-4525-8268-24c77d0ee6b2
        userCondition: null
fs: blogImagesFilesystem
handle: blogImages
name: 'Blog Images'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
