altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1dca67b0-ec7d-43c0-8441-079dbe56b214:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-28T23:49:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 27959e92-03bb-4f10-a85a-7db469ac4788
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1cd0c4d9-d730-4f23-b985-51fcb7477a68
        userCondition: null
fs: iconsFilesystem
handle: icons
name: Icons
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
