altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c21a9850-d6d1-418e-845c-6ce40a94195b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T15:32:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 188e7bab-87cc-4f02-8306-e9ee766e3ef5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39f4d459-c1cf-4d5f-925e-e8445cb990f5
        userCondition: null
fs: portfolioImagesFilesystem
handle: portfolioImages
name: 'Portfolio Images'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
