columnSuffix: null
handle: cardPosition
instructions: null
name: 'Card Position'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Off'
        -
          - value
          - 'off'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
