columnSuffix: null
handle: homepageBlocks
instructions: null
name: 'Homepage Blocks'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - f38e7b86-9c80-45f7-9c24-03e61e14abf6 # Hero Block
    - 78cd8c82-7d01-4597-9562-f8383ff843c5 # Featured Works Block
    - 9dffce5e-9785-4d43-9780-bd0a2c39d141 # Slider Block
    - 7cfa1850-34c5-4ccc-9135-a2d131dc732e # Two Column Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
