columnSuffix: null
handle: leftColumnContent
instructions: null
name: 'Left Column Content'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - f0a7b6f4-0e83-455e-aba3-24ce98fa11dc # Page Header
    - 52aac039-0add-491a-bf95-a4310c1e1a74 # Page Content
    - 6b800eda-1b70-4f2b-90dc-4ea35a2a6894 # Page Spacer
    - 452561b9-4d58-4e06-abbb-ec181d217e97 # Page Subtitle with Content
    - 33982884-3ffc-4b10-ab0f-7acce9c2f4e6 # Page Callout Box
    - e2e8232d-7a91-4520-9f64-0d0c97df5efc # Page Gallery
    - eb0ea69f-509b-47a6-87cb-c9f3ad376908 # Page Form
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
