columnSuffix: null
handle: pageBuilderOptionLeftColumnWidth
instructions: "The left and right column width each have a grid width spanning 8 columns each. Choose whether to make the left column smaller or larger. The right column will expand or shrink based on the left column's width."
name: 'Page Builder Option: Left Column Width'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '6'
        -
          - value
          - '6'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '8'
        -
          - value
          - '8'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '10'
        -
          - value
          - '10'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '12'
        -
          - value
          - '12'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
