columnSuffix: null
handle: pageBuilder
instructions: null
name: 'Page Builder'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - b28d4120-dd8f-47c8-9968-e484ce2daf49 # Page Builder: Split Content Row
    - 82a2a030-6246-4333-af89-a21865e574c4 # Page Builder: Full Content Row
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
