columnSuffix: null
handle: pageCalloutColumns
instructions: null
name: 'Page Callout Columns'
searchable: false
settings:
  createButtonLabel: 'Add Page Callout Column'
  entryTypes:
    - 452561b9-4d58-4e06-abbb-ec181d217e97 # Page Builder: Subtitle with Content Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
