columnSuffix: null
handle: pageSlideLink
instructions: null
name: 'Page Slide: Link'
searchable: false
settings:
  maxLength: 255
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
  types:
    - url
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
