columnSuffix: null
handle: splitMediaBlockReverse
instructions: 'Instead of the image on the left, the image will appear on the right (if applicable).'
name: 'Split Media Block Reverse'
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
