columnSuffix: null
handle: twoColumnBlockLayout
instructions: null
name: 'Two Column Block Layout'
searchable: false
settings:
  default: false
  offLabel: Condensed
  onLabel: 'Full Width'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
