columnSuffix: null
handle: twoColumnBlockMobileLayout
instructions: 'Choose whether or not to have the content or image appear first in mobile. Content will be first by default.'
name: 'Two Column Block Mobile Layout'
searchable: false
settings:
  default: true
  offLabel: 'Image First'
  onLabel: 'Content First'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
