defaultPlacement: end
enableVersioning: true
entryTypes:
  - b28d4120-dd8f-47c8-9968-e484ce2daf49 # Split Content Block
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - Page
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/base.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 4c0a1eed-b32a-43d6-ad31-77d4dc6ba447
type: structure
