defaultPlacement: end
enableVersioning: true
entryTypes:
  - 298cea5e-e970-4f91-91b6-21ba893e3458 # Photo
handle: photos
maxAuthors: 1
name: Photos
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: photo/_entry.twig
    uriFormat: 'photo/{slug}'
type: channel
